Repository APPS-sookmyung/2024-OUTFOOT-client, pull requests merged in 2024-10, with the labels that each got.

#27 [Network] #23 - 도장판 api 연결 및 네트워크 세팅
  outfoot/.gitignore
  outfoot/lib/api/personal_goal_api.dart
  outfoot/lib/main.dart
  outfoot/lib/models/personal_goal_model.dart
  outfoot/lib/screens/login/login_find_id.dart
  outfoot/lib/screens/login/login_find_pw.dart
  outfoot/lib/screens/login/login_page_screen.dart
  outfoot/lib/screens/login/start_login_page_screen.dart
  outfoot/lib/screens/make_goal/make_personal_goal.dart
  outfoot/pubspec.lock
  outfoot/pubspec.yaml
Labels: 🛜Network, 🫧지원, ⚙️Setting

#32 [Fix#30] color.dart 적용
  outfoot/lib/colors/colors.dart
  outfoot/lib/screens/add_friend_popup_screen.dart
  outfoot/lib/screens/add_friend_screen.dart
  outfoot/lib/screens/friend_list_screen.dart
Labels: 📱Style, ☁️서연, 🎡Chore

#31 [Feat/#24] profilemypage UI 생성
  outfoot/assets/people_icon.svg
  outfoot/lib/screens/profile_my_page.dart
  outfoot/lib/widgets/dashed_path_painter.dart
  outfoot/pubspec.lock
  outfoot/pubspec.yaml
Labels: 📱Style, ☁️서연, 🧩Feat

#34 [Feat/#33] editprofilepage UI 생성
  outfoot/lib/screens/edit_profile_page.dart
  outfoot/pubspec.lock
  outfoot/pubspec.yaml
Labels: 📱Style, ☁️서연, 🧩Feat
