Repository APPS-sookmyung/2024-OUTFOOT-client, pull requests merged in 2024-09, with the labels that each got.

#8 [Feat/#2] checkpage_foot UI 구현
  outfoot/assets/back_icon.svg
  outfoot/assets/delete_icon.svg
  outfoot/assets/floating_action.svg
  outfoot/assets/home.svg
  outfoot/assets/paw.svg
  outfoot/assets/profile.svg
  outfoot/assets/search.svg
  outfoot/assets/share_icon.svg
  outfoot/assets/shuffle_icon.svg
  outfoot/lib/screens/checkpage_foot.dart
  outfoot/lib/screens/navigation_bar/bottom_navigation_bar.dart
  outfoot/lib/screens/navigation_bar/material_top_navigation_bar.dart
  outfoot/lib/widgets/custom_floating_action_button.dart
  outfoot/pubspec.lock
  outfoot/pubspec.yaml
Labels: 📱Style, 🧡해림

#10 [Feat/#9] checkpage_image UI 구현
  outfoot/lib/screens/checkpage_image.dart
  outfoot/pubspec.lock
  outfoot/pubspec.yaml
Labels: 📱Style, 🧡해림

#12 [Feat/#11] upload UI 구현
  outfoot/assets/arrow.svg
  outfoot/lib/screens/upload.dart
  outfoot/linux/flutter/generated_plugin_registrant.cc
  outfoot/linux/flutter/generated_plugins.cmake
  outfoot/macos/Flutter/GeneratedPluginRegistrant.swift
  outfoot/pubspec.lock
  outfoot/pubspec.yaml
  outfoot/windows/flutter/generated_plugin_registrant.cc
  outfoot/windows/flutter/generated_plugins.cmake
Labels: 📱Style, 🧡해림

#16 [Feat/#15] homepage UI 구현
  outfoot/assets/alarm_icon.svg
  outfoot/assets/lock_icon.svg
  outfoot/assets/logo.svg
  outfoot/lib/screens/home_page.dart
  outfoot/lib/screens/navigation_bar/top_navigation_bar.dart
  outfoot/lib/widgets/target_view.dart
  outfoot/pubspec.yaml
Labels: 📱Style, 🧡해림

#7 [Feat] #1 - 로그인 페이지 UI 구현
  outfoot/assets/login_image1.svg
  outfoot/assets/login_image2.svg
  outfoot/assets/logo.svg
  outfoot/assets/start_login_logo.svg
  outfoot/lib/main.dart
  outfoot/lib/screens/login_page_screen.dart
  outfoot/lib/screens/start_login_page_screen.dart
  outfoot/pubspec.lock
  outfoot/pubspec.yaml
Labels: 📱Style, 🫧지원, 🧩Feat

#18 [Feat] #17 - 로그인 아이디/비밀번호 찾기 UI 구현
  outfoot/.metadata
  outfoot/ios/Flutter/Debug.xcconfig
  outfoot/ios/Flutter/Release.xcconfig
  outfoot/ios/Podfile
  outfoot/lib/main.dart
  outfoot/lib/screens/login_find_id.dart
  outfoot/lib/screens/login_find_pw.dart
  outfoot/macos/Flutter/Flutter-Debug.xcconfig
  outfoot/macos/Flutter/Flutter-Release.xcconfig
  outfoot/macos/Podfile
  outfoot/pubspec.lock
  outfoot/pubspec.yaml
Labels: 📱Style, 🫧지원, 🧩Feat

#21 [Feat/#19] 모달창 포함 UI 구현
  outfoot/assets/yellow_smile_icon.svg
  outfoot/ios/Podfile
  outfoot/lib/main.dart
  outfoot/lib/screens/make_goal/make_personal_goal.dart
  outfoot/pubspec.yaml
Labels: 📱Style, 🫧지원, 🧩Feat

#22 [Feat] #20 - 컬러코드 colors.dart에 정리
  outfoot/ios/Podfile
  outfoot/lib/colors/colors.dart
Labels: 📱Style, 🫧지원, ⚙️Setting

#26 [Fix/#25] colors.dart 적용
  outfoot/lib/colors/colors.dart
  outfoot/lib/screens/checkpage_foot.dart
  outfoot/lib/screens/checkpage_image.dart
  outfoot/lib/screens/checkpage_photodetail_memo.dart
  outfoot/lib/screens/home_page.dart
  outfoot/lib/screens/login_find_id.dart
  outfoot/lib/screens/login_page_screen.dart
  outfoot/lib/screens/make_goal/make_personal_goal.dart
  outfoot/lib/screens/navigation_bar/bottom_navigation_bar.dart
  outfoot/lib/screens/navigation_bar/comment_bottom_navigation_bar.dart
  outfoot/lib/screens/navigation_bar/material_top_navigation_bar.dart
  outfoot/lib/screens/navigation_bar/top_navigation_bar.dart
  outfoot/lib/screens/start_login_page_screen.dart
  outfoot/lib/screens/upload.dart
  outfoot/pubspec.lock
  outfoot/pubspec.yaml
  outfoot/test/widget_test.dart
Labels: 📱Style, 🧡해림, 🎡Chore
